# Generated by Django 5.0.1 on 2026-02-21 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=128, unique=True)),
                ('total_classrooms', models.PositiveIntegerField(default=0)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('max_weekly_hours', models.PositiveIntegerField(default=0)),
                ('assigned_hours', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('registration_number', models.CharField(max_length=64, unique=True)),
                ('semester', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.CharField(max_length=128)),
                ('seating_capacity', models.PositiveIntegerField(default=0)),
                ('current_strength', models.PositiveIntegerField(default=0)),
                ('is_smart_class', models.BooleanField(default=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='campus.block')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=32, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('enrolled_students', models.PositiveIntegerField(default=0)),
                ('weekly_hours', models.PositiveIntegerField(default=0)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='campus.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='campus.course')),
            ],
        ),
    ]
