# Generated by Django 5.0.1 on 2026-02-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='registration_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
