# Generated by Django 5.0.1 on 2026-02-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_faculty_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
